<?php
return [
    '' => 'site/index',
    // '' => 'sitev1/index',
    // 'v2' => 'sitev2/index',

    'tim-kiem-<keyword:[0-9a-z\-]+>/<cname:[0-9a-z\-]+>-c<cid:[0-9]+>/<sname:[0-9a-z\-]+>-s<sid:[0-9]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'product/browse',
    'tim-kiem-<keyword:[0-9a-z\-]+>/<cname:[0-9a-z\-]+>-c<cid:[0-9]+>/<sname:[0-9a-z\-]+>-s<sid:[0-9]+>' => 'product/browse',
    'tim-kiem-<keyword:[0-9a-z\-]+>/<cname:[0-9a-z\-]+>-c<cid:[0-9]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'product/browse',
    'tim-kiem-<keyword:[0-9a-z\-]+>/<cname:[0-9a-z\-]+>-c<cid:[0-9]+>' => 'product/browse',
    'tim-kiem-<keyword:[0-9a-z\-]+>/<sname:[0-9a-z\-]+>-s<sid:[0-9]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'product/browse',
    'tim-kiem-<keyword:[0-9a-z\-]+>/<sname:[0-9a-z\-]+>-s<sid:[0-9]+>' => 'product/browse',
    'tim-kiem-<keyword:[0-9a-z\-]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'product/browse',
    'tim-kiem-<keyword:[0-9a-z\-]+>' => 'product/browse',
    'tim-kiem' => 'product/browse',
    '<cname:[0-9a-z\-]+>-c<cid:[0-9]+>/<sname:[0-9a-z\-]+>-s<sid:[0-9]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'product/browse',
    '<cname:[0-9a-z\-]+>-c<cid:[0-9]+>/<sname:[0-9a-z\-]+>-s<sid:[0-9]+>' => 'product/browse',
    '<cname:[0-9a-z\-]+>-c<cid:[0-9]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'product/browse',
    '<cname:[0-9a-z\-]+>-c<cid:[0-9]+>' => 'product/browse',
    '<sname:[0-9a-z\-]+>-s<sid:[0-9]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'product/browse',
    '<sname:[0-9a-z\-]+>-s<sid:[0-9]+>' => 'product/browse',
    '<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'product/browse',

    'tin-tuc-<keyword:[0-9a-z\-]+>' => 'news/browse',
    'tin-tuc' => 'news/browse',
    '<cname:[0-9a-z\-]+>-c<cid:[0-9]+>/<sname:[0-9a-z\-]+>-s<sid:[0-9]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'news/browse',
    '<cname:[0-9a-z\-]+>-c<cid:[0-9]+>/<sname:[0-9a-z\-]+>-s<sid:[0-9]+>' => 'news/browse',
    '<cname:[0-9a-z\-]+>-c<cid:[0-9]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'news/browse',
    '<cname:[0-9a-z\-]+>-c<cid:[0-9]+>' => 'news/browse',
    '<sname:[0-9a-z\-]+>-s<sid:[0-9]+>/<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'news/browse',
    '<sname:[0-9a-z\-]+>-s<sid:[0-9]+>' => 'news/browse',
    '<pvname:[0-9a-z\-]+>-pv<pvid:[0-9]+>' => 'news/browse',
    
    'mall' => 'mall/index',
    'gio-hang' => 'product/cart',

    'gioi-thieu.html' => 'site/about',
    'dang-ky-nguoi-ban-hang-lien-ket.html' => 'user/affiliate',
    'lien-he.html' => 'site/contact',
    'khach-hang.html' => 'user/index',
    'doi-mat-khau.html' => 'user/password',
    'lich-su-mua-hang.html' => 'user/order',
    '<name:[0-9a-z\-]+>-c<cid:[0-9]+>-p<id:[0-9]+>.html' => 'product/detail',
    '<name:[0-9a-z\-]+>-p<id:[0-9]+>.html' => 'product/detail',
    '<name:[0-9a-z\-]+>-n<id:[0-9]+>.html' => 'news/detail',
    'o2o/<code:[0-9a-zA-Z]+>.html' => 'o2o/detail',
    'hoa-don/<oid:[0-9a-z\-]+>' => 'product/bill',
    'xac-nhan/<oid:[0-9a-z\-]+>' => 'order/confirm',
    'kiem-tra-don-hang.html' => 'order/check',
    'online-friday-2017.html' => 'site/friday',
    'dac-san-ben-tre.html' => 'site/friday',
    'danh-sach-dia-chi-nhan-hang.html' => 'user/address',
    'ban-hang-cung-voso.html' => 'auth/signupmerchant',
    'dang-ky-nguoi-ban.html' => 'auth/personal',
    'doanh-nghiep-dang-ky.html' => 'auth/enterprise',
    'tao-chien-dich-ban-hang-lien-ket.html' => 'user/o2o',
    'danh-sach-chien-dich-ban-hang-lien-ket.html' => 'user/list-o2o',
    'danh-sach-don-hang-ban-hang-lien-ket.html' => 'user/list-o2o-order',
    'chinh-sua-thong-tin-ban-hang-lien-ket.html' => 'user/edit-affiliate-information',
    'tao-chien-dich-ban-hang-lien-ket.html' => 'user/create-o2o-campaign',
    'admin' => 'site/admin',

    //webhook cập nhật trạng thái viettelpost 
    'viettelpost/update-status' => 'webhook/viettelpost',
    'login/<authclient:[0-9a-z\-]+>' => 'site/auth',
];
